import { Home, FileText, CheckSquare, Calendar, Monitor, Search, MessageCircle, HelpCircle, Settings } from 'lucide-react'

export const sectionColors: Record<string, string> = {
  home: 'text-orange-500',
  memos: 'text-blue-500',
  memo: 'text-blue-500',
  'memo-edit': 'text-blue-500',
  tables: 'text-indigo-500',
  'table-edit': 'text-indigo-500',
  todos: 'text-emerald-500',
  todo: 'text-emerald-500',
  calendar: 'text-rose-500',
  event: 'text-rose-500',
  tools: 'text-violet-500',
  tool: 'text-violet-500',
  search: 'text-amber-500',
  chat: 'text-cyan-500',
  help: 'text-teal-500',
  settings: 'text-zinc-400',
}

export const sectionBgColors: Record<string, string> = {
  home: 'bg-orange-500/10',
  memos: 'bg-blue-500/10',
  memo: 'bg-blue-500/10',
  'memo-edit': 'bg-blue-500/10',
  tables: 'bg-indigo-500/10',
  'table-edit': 'bg-indigo-500/10',
  todos: 'bg-emerald-500/10',
  todo: 'bg-emerald-500/10',
  calendar: 'bg-rose-500/10',
  event: 'bg-rose-500/10',
  tools: 'bg-violet-500/10',
  tool: 'bg-violet-500/10',
  search: 'bg-amber-500/10',
  chat: 'bg-cyan-500/10',
  help: 'bg-teal-500/10',
  settings: 'bg-zinc-500/10',
}

export const sectionBorderColors: Record<string, string> = {
  home: 'border-orange-400',
  memos: 'border-blue-400',
  memo: 'border-blue-400',
  'memo-edit': 'border-blue-400',
  tables: 'border-indigo-400',
  'table-edit': 'border-indigo-400',
  todos: 'border-emerald-400',
  todo: 'border-emerald-400',
  calendar: 'border-rose-400',
  event: 'border-rose-400',
  tools: 'border-violet-400',
  tool: 'border-violet-400',
  search: 'border-amber-400',
  chat: 'border-cyan-400',
  help: 'border-teal-400',
  settings: 'border-zinc-400',
}

export const sectionBgSolid: Record<string, string> = {
  home: 'bg-orange-500',
  memos: 'bg-blue-500',
  memo: 'bg-blue-500',
  'memo-edit': 'bg-blue-500',
  tables: 'bg-indigo-500',
  'table-edit': 'bg-indigo-500',
  todos: 'bg-emerald-500',
  todo: 'bg-emerald-500',
  calendar: 'bg-rose-500',
  event: 'bg-rose-500',
  tools: 'bg-violet-500',
  tool: 'bg-violet-500',
  search: 'bg-amber-500',
  chat: 'bg-cyan-500',
  help: 'bg-teal-500',
  settings: 'bg-zinc-500',
}

export const sectionIcons: Record<string, typeof Home> = {
  home: Home,
  memos: FileText,
  memo: FileText,
  'memo-edit': FileText,
  todos: CheckSquare,
  todo: CheckSquare,
  calendar: Calendar,
  event: Calendar,
  tools: Monitor,
  tool: Monitor,
  search: Search,
  chat: MessageCircle,
  help: HelpCircle,
  settings: Settings,
}
